version: '3'
services:
  example.org:
    image: flashspys/nginx-static
    container_name: example.org
    ports:
      - 8080:80
    volumes:
      - ./build:/static
      - /root/arbshot_gui/.htpasswd:/etc/nginx/.htpasswd
      - /root/arbshot_gui/my_nginx_conf.conf:/etc/nginx/conf.d/default.conf
